### ISSUE TITLE
Not working on my 2.9 / Python 3 installation

### ISSUE THREAD

**Issue by armori** [ckan/ckanext-pdfview#43]
Installed in a 2.8 / Python 2 it works like a charm, but in 2.9 / Python 3 when I open the view page, it automatically downloads the PDF to my PC and the view is just a blank.

**Comment by reinevizcarra** [comment]
Hi @armori did you ever figure this out? I currently have the same problem.

**Comment by armori** [comment]
@rvizcarra-eclipse unfortunately I couldn't. And this isn't the only extension that just doesn't work properly in CKAN 2.9 / Python 3.

**Comment by reinevizcarra** [comment]
@armori I tried to ask someone on the gitter chat regarding this and they said that it's running fine in the [demo](https://demo.ckan.org/) and that there is something wrong with our chrome build which I'm not entirely sure what they mean.

**Comment by jonathansberry** [comment]
@amercader I think the problem here, if I'm not mistaken, is that [version 0.0.7 has not yet been pushed to Pypi](https://pypi.org/project/ckanext-pdfview/#history).  

I am getting version 0.0.6 when I install the extension by pip - it is missing the "preview=1" arg in the object source attribute [here...](https://github.com/ckan/ckanext-pdfview/blob/41ef938b607a83eba19b66112176fa046dadf5fc/ckanext/pdfview/theme/templates/pdf_view.html#L1)

This is causing PDFs to download automatically rather than previewing properly in-screen.  The matter is fixed in 0.0.7, but this isn't available from pypi yet.  Hope that is helpful.

**Comment by crstn-aiw** [comment]
Hi,
I encountered a similar error with this and tried what I have read here but it is still throwing me the error.
I have the latest ckan 2.9, python 3.8 on ubuntu 20.04 from package
Any ideas? thank you
=======================errror==========================
File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 282, in _get_service
raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: pdf_view
=======================errror==========================

**Comment by reinevizcarra** [comment]
Hi @crstn-aiw, 
When I had this issue, there weren't any errors in the log files but the pdf viewer wasn't showing up. Whenever the page was visited, it automatically downloaded the file and that's how we knew it was broken. Do you have the same issue? At that time, we fixed it by upgrading our python version to 3.8...

Your error suggests that it can't find that pdf_view plugin - did you install it before adding it to your .ini file? 

Hope this helps!

**Comment by crstn-aiw** [comment]
Hi @rvizcarra-eclipse thanks for response, 
yes, it always downloads the pdf for me too, I did install the plugin first before adding to .ini file and my python is 3.8.10.. i've been poking around and think maybe i need to redo it. Would you know what is best way to do a clean re-install of the pdf_view plugin and remove any related references in some folders (I am new to linux & ckan)? thank you

**Comment by reinevizcarra** [comment]
Hey @crstn-aiw,
`pip uninstall ckanext-pdfview` should do the trick :) `pip list` to list all of the plugins that you have installed.
